name: roux
description: >-
  A Lightweight, fast router for Dart with expressive pathname syntax.
version: 0.4.0
repository: https://github.com/medz/roux

funding:
  - https://github.com/sponsors/medz

topics:
  - router
  - http
  - path-matching
  - trie

environment:
  sdk: ^3.10.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  lints: ^6.0.0
  relic: ^1.0.0
  spanner: ^1.0.6
  test: ^1.28.0
